---
title: "Heatmaps in R"
author: "Lisa Cao"
date: "January 29, 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Heatmaps in R
Using heatmap() and heatmaply()

By Lisa N. Cao


## About Me

- RLadies Vancouver Co-Organizer (connect with us on Meetup.com!)
- Second SciProg Workshop
- SFU Psychology Department 
- Twitter: @Lisancao

## Introduction
"A heatmap is a popular graphical method for visualizing high-dimensional data, in which a table of numbers are encoded as a grid of colored cells. 

The rows and columns of the matrix are ordered to highlight patterns and are often accompanied by dendrograms. Heatmaps are used in many fields for visualizing observations, correlations, missing values patterns, and more."

## HeatMaps
  - Today we're pretty much delving into the very vast landscape of heatmaps, but sticking with just base R and heatmaply package to get you use to different outputs
 
  - There are many different ways to generate heatmaps, differences between all of them are minor syntax differences, clustering algorithms, and aesthetic
  
  - heatmap, heatmap.2 (package gplots), heatmap.3 (package GMD), heatmap.plus, aheatmap (package NMF), pheatmap, ggheat, heatmaply, d3heatmap, ComplexHeatmap, Superheat, Heatplus, geomtile (ggplot2)

## Data types that are suitable for Heatmaps 
  - High dimensional data, such as genomic data, time-series data, or geospatial just to name a few 
  - Best to work with a dataset that has an assumed normal distribution, there are some solutions presented with heatmaply() such as normalize() and percentalize() 

##packages today
  - base R
  - mtcars
  - RColorBrewer
  - heatmaply

##RColorBrewer
-An excellent supplement to increasing the number of colour palettes in R 
The colours are split into three group, sequential, diverging, and qualitative.
  
   -  Sequential - Light colours for low data, dark for high data
   
   -  Diverging -  Light colours for mid-range data, low and high contrasting dark colours
   
   -  Qualitative - Colours designed to give maximum visual difference between classes

The main function is brewer.pal, which you simply give the number of colours you want, and the name of the palette, which you can choose from running display.brewer.all()

##Heatmaply
  - Interactiveness allows for the inspection of specific value by hovering the mouse over a cell, as well as zooming into a region of the heatmap by dragging a rectangle around the relevant area.
  
  - This work is based on the ggplot2 and plotly.js engine. It produces similar heatmaps as d3heatmap, with the advantage of speed (plotly.js is able to handle larger size matrix), and the ability to zoom from the dendrogram.

##install packages
```
install.packages("heatmaply")
install.packages("RColorBrewer")
#install.packages("mtcars")
```

##import libraries
```
library(mtcars)
library("heatmaply")
library("RColorBrewer")
```

##import in mtcars as matrix, view data
```
mtcars <- as.matrix(mtcars)
head(mtcars)
View(mtcars)
```
##Scaling
If we would assume all variables come from some normal distribution, then scaling (i.e.: subtract the mean and divide by the standard deviation) would bring them all close to the standard normal distribution. In such a case, each value would reflect the distance from the mean in units of standard deviation. 

##Prescaling the data: scale data to mean=0, sd=1 and convert to matrix
```
mtscaled <- as.matrix(scale(mtcars))
``` 

##Scaling as a plot attribute instead
```
heatmap(mtcars)
heatmap(mtcars, scale="column")
```

##clusterization notes
The order of both rows and columns is different compare to the native mtcar matrix because heatmaps do a reordering using clusterisation: it calculates the distance between each pair of rows and columns and tries to order them by similarity. 

Moreover, the corresponding dendrogram are provided beside the heatmap. We can avoid it and just visualize the raw matrix: use the Rowv and Colv arguments.

##plot raw matrix without reordering, this automatically excludes the dendrogram
No dendrogram nor reordering for neither column or row
```
heatmap(mtcars, Colv = NA, Rowv = NA, scale="column")
```

##colour palette customization
there are basic colour palettes you can use that come with base R, with more options being available in the RColorBrewer package
```
#cyan-magenta in base
heatmap(mtcars, scale ="column", col=cm.colors(256))
#terrain 
heatmap(mtcars, scale ="column", col=terrain.colors(256))
```

##using RColorBrewer
```
#rcolorbrewer palettes
display.brewer.all()
heatmap(mtcars, scale = "column", col=brewer.pal(8, "BuGn"))
```

##add x and y labels
```
heatmap(mtcars, Colv = NA, Rowv = NA, scale = "column", col=brewer.pal(8, "BuGn"), xlab = "Variables", ylab = "Cars", main = "Mtcars Heatmap")
```
```
##edit labrow labels, size, and margins
```
heatmap(mtcars, Colv = NA, Rowv = NA, scale = "column", col=brewer.pal(8, "BuGn"), 
        xlab = "Variables", ylab = "Cars", main = "Mtcars Heatmap",
        cexRow = 1, cexCol = 1,
        labRow = paste(rownames(mtcars), sep = ""),
        labCol = paste(colnames(mtcars), sep = ""), 
        margins=c(5,10))```
```
##adding in a colour guide using RowSideColors
```
guide=as.numeric(as.factor(substr(rownames(mtcars), 1, 1)))
guide_col=brewer.pal(9, "BuGn")[guide]
```
##print final heatmap made in base R
```
baser_heatmap <- heatmap(mtcars, Colv = NA, Rowv = NA, scale = "column", col=brewer.pal(8, "BuGn"), 
        xlab = "Variables", ylab = "Cars", main = "Mtcars Heatmap",
        cexRow = 1, cexCol = 1,
        labRow = paste(rownames(mtcars), sep = ""),
        labCol = paste(colnames(mtcars), sep = ""), 
        RowSideColors = guide_col, 
        margins=c(5,10))
```

##Using Heatmaply 
```
heatmaply(mtcars)

```
##HeatMaply Notes
By default heatmaply tries to fix the margins of the plot based on the length of the labels, but this system is not perfect. Hence, we sometimes need to manually fix the margins (hopefully this will be fixed in future versions of plotly). This is also helpful when including xlab/ylab/main texts.

##add in some titles and edit margins
```
heatmaply(mtcars, xlab = "Features", ylab = "Cars", 
          main = "Heatmap of mtcars with Heatmaply",
          margins = c(60,100,40,20))
```
##scale using columns
```
heatmaply(mtcars, xlab = "Features", ylab = "Cars", 
          main = "Scaled Heatmap of mtcars with Heatmaply",
          margins = c(60,100,40,20),
          scale = "column")
```
##map the variables against themselves to create a correlation heatmap 
```
heatmaply(cor(mtcars), margins = c(40, 40),
          k_col = 2, k_row = 2,
          xlab = "", ylab = "", 
          main = "Correlation with Heatmaply")
```
##normalize the variables
```
heatmaply(normalize(mtcars), xlab = "Features", ylab = "Cars", 
          main = "Normalized Heatmap of mtcars with Heatmaply'",
          margins = c(60,100,40,20))
```
##NA Identification
```
#identifying NA's using heatmaply_na()
```
heatmaply_na(mtcars, k_col =3, k_row = 3, margins = c(55, 30))
```
#testing it out on a dataset that actually has NA's
```
heatmaply_na(airquality, k_col =3, k_row = 3, margins = c(55, 30))
```


##changing colours 
```
display.brewer.all()
BuGn <- colorRampPalette(brewer.pal(9, "BuGn"))

heatmaply(mtcars, xlab = "Features", ylab = "Cars", 
          main = "Scaled Heatmap of mtcars with Heatmaply",
          margins = c(60,100,40,20),
          colors = BuGn,
          scale = "column")
```
##saving it as well
```
heatmaply(cor(mtcars), margins = c(40, 40),
          k_col = 2, k_row = 2,
          colors = BuGn,
          limits = c(-1,1),
          file = "folder/heatmaply_plot.png",
          browseURL("folder/heatmaply_plot.png"))
```
##saving the plot

##interactive version
```
dir.create("heatmaps")
heatmaply(mtcars, file = "heatmaps/heatmaply_plot.html")
browseURL("folder/heatmaply_plot.html")

webshot::install_phantomjs()
```
##static version
```
heatmaply(mtcars, file = "heatmaps/heatmaply_plot.png")
browseURL("heatmaps/heatmaply_plot.png")
```







##Resources used for this workshop 
https://www.r-graph-gallery.com/215-the-heatmap-function/
https://www.r-bloggers.com/drawing-heatmaps-in-r/
https://www.biostars.org/p/205417/
https://cran.r-project.org/web/packages/heatmaply/vignettes/heatmaply.html
https://www.r-bloggers.com/r-using-rcolorbrewer-to-colour-your-figures-in-r/


##RLadies is looking for speakers!
If you or someone you know is interested in giving a beginner's talk for our organization (downtown area, month of April in the evening), email me at lisanatashacao@gmail.com :)

